/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <errno.h>

calc_res *
suma_1_svc(double arg1, char arg2, double arg3,  struct svc_req *rqstp)
{
	static calc_res result;

	if (arg2!='+' && arg2!='-' && arg2!='x' && arg2!='/')
	{
		result.errnum = errno;
		return (&result);
	}

	xdr_free(xdr_calc_res, &result);

	switch(arg2){
		case '+':
			result.calc_res_u.res = arg1 + arg3;
			break;
		case '-':
			result.calc_res_u.res = arg1 - arg3;
			break;
		case 'x':
			result.calc_res_u.res = arg1 * arg3;
			break;
		case '/':
			if(arg3==0){
				result.errnum = errno;
				return (&result);
			}
			result.calc_res_u.res = arg1 / arg3;
			break;
	}

	return &result;
}
