/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calcop_1(char *host, double arg1, char arg2, double arg3)
{
	CLIENT *clnt;
	calc_res  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCOP, SIMPLE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(arg1, arg2, arg3, clnt);
	if (result_1 == (calc_res *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	if (result_1->errnum != 0)
	{
		printf("Error: %s\n", strerror(result_1->errnum));
		exit(1);
	}
	else
	{
		printf("Resultado: %f\n", result_1->calc_res_u.res);
	}

	xdr_free(xdr_calc_res, result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	exit(0);
}


int
main (int argc, char *argv[])
{
	char *host;
	double num1;
	char oper;
	double num2;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	num1 = atof(argv[2]);
	oper = *argv[3];
	num2 = atof(argv[4]);

	calcop_1 (host, num1, oper, num2);
}
