/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calc_res {
	int errnum;
	union {
		double res;
	} calc_res_u;
};
typedef struct calc_res calc_res;

struct bin_1_argument {
	double arg1;
	char arg2;
	double arg3;
};
typedef struct bin_1_argument bin_1_argument;

#define CALCBIN 0x20000001
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define BIN 1
extern  calc_res * bin_1(double , char , double , CLIENT *);
extern  calc_res * bin_1_svc(double , char , double , struct svc_req *);
extern int calcbin_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BIN 1
extern  calc_res * bin_1();
extern  calc_res * bin_1_svc();
extern int calcbin_1_freeresult ();
#endif /* K&R C */

struct un_1_argument {
	char arg1;
	double arg2;
};
typedef struct un_1_argument un_1_argument;

#define CALCUN 0x20000002
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define UN 1
extern  calc_res * un_1(char , double , CLIENT *);
extern  calc_res * un_1_svc(char , double , struct svc_req *);
extern int calcun_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UN 1
extern  calc_res * un_1();
extern  calc_res * un_1_svc();
extern int calcun_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calc_res (XDR *, calc_res*);
extern  bool_t xdr_bin_1_argument (XDR *, bin_1_argument*);
extern  bool_t xdr_un_1_argument (XDR *, un_1_argument*);

#else /* K&R C */
extern bool_t xdr_calc_res ();
extern bool_t xdr_bin_1_argument ();
extern bool_t xdr_un_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
