/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static calc_res *
_bin_1 (bin_1_argument *argp, struct svc_req *rqstp)
{
	return (bin_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static calc_res *
_un_1 (un_1_argument *argp, struct svc_req *rqstp)
{
	return (un_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
calcbin_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		bin_1_argument bin_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case BIN:
		_xdr_argument = (xdrproc_t) xdr_bin_1_argument;
		_xdr_result = (xdrproc_t) xdr_calc_res;
		local = (char *(*)(char *, struct svc_req *)) _bin_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calcun_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		un_1_argument un_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case UN:
		_xdr_argument = (xdrproc_t) xdr_un_1_argument;
		_xdr_result = (xdrproc_t) xdr_calc_res;
		local = (char *(*)(char *, struct svc_req *)) _un_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCBIN, PRIMERA);
	pmap_unset (CALCUN, PRIMERA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCBIN, PRIMERA, calcbin_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCBIN, PRIMERA, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCUN, PRIMERA, calcun_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCUN, PRIMERA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCBIN, PRIMERA, calcbin_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCBIN, PRIMERA, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCUN, PRIMERA, calcun_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCUN, PRIMERA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
